# SERVICES
services:
  # Database Service (PostgreSQL)
  postgres_db:
    image: postgres:15-alpine
    container_name: admin_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - admin-data:/var/lib/postgresql/data
    networks:
      - shared_network
    ports:
      - "5440:5432" # Public port 5440 VPS

  # Backend Service (Node.js/Express)
  backend:
    build: ./backend
    container_name: admin_backend
    restart: unless-stopped
    ports:
      - "3033:3000"  # Public port 3033 VPS
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - shared_network

# NETWORK
networks:
  shared_network:
    external: true

# VOLUME
volumes:
  admin-data:
    driver: local