export enum CompanyType {
  AGENCY_STUDIO = 'AGENCY_STUDIO',
  TECH_STARTUP = 'TECH_STARTUP',
  SOFTWARE_COMPANY = 'SOFTWARE_COMPANY',
  INDUSTRY = 'INDUSTRY',
  ECOMMERCE = 'ECOMMERCE',
  FREELANCE_COLLECTIVE = 'FREELANCE_COLLECTIVE',
}

export enum Status {
  BACKLOG = 'BACKLOG',
  TO_CONTACT = 'TO_CONTACT',
  WAITING = 'WAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  ARCHIVED = 'ARCHIVED',
  HIRED = 'HIRED',
}